#!/bin/bash

#expand 
# : converts tab to space
# uniq -u
# : silent rest of output
#awk -F: '{printt $1;}
# : print the first field after colon

ifconfig | expand | cut -c1-8 | sort | uniq -u | awk -F: '{print $1;}'
